apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-test-clusterrole-binding
  namespace: kube-test
subjects:
- kind: ServiceAccount
  name: kube-test-sa
  namespace: users
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io