apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: kube-test
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: sa
      containers:
        - name: frontend
          image: kube-test-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 1
              memory: "2Gi"
            requests:
              cpu: 0.5
              memory: '1Gi'