pipeline {
    agent any

    environment {
        ENV = """${sh(
            returnStdout: true,
            script: echo "dev"
        )}"""
        
        NAMESPACE = 'devops-tools'

        // Type: SecretText
        SECRET_TEXT = credentials('secret-id')

        // Type: Username/Password
        // DOCKER_CREDS - contains a username and a password separated by a colon in the format username:password.
        // DOCKER_CREDS_USR - an additional variable containing the username component only.
        // DOCKER_CREDS_PSW - an additional variable containing the password component only.
        DOCKER_CREDS = credentials('docker-creentials')

        // Type: File
        // The MY_KUBECONFIG environment variable will be assigned
        // the value of a temporary file.  For example:
        //   /home/user/.jenkins/workspace/cred_test@tmp/secretFiles/546a5cf3-9b56-4165-a0fd-19e2afe6b31f/kubeconfig.txt
        MY_KUBECONFIG = credentials('my-kubeconfig')
    }

    parameters {
        string(name: 'ENVIRONMENT', defaultValue: 'DEV', description: 'Which environment to deploy this pod in')
    }

    stages {
        stage('Checkout') {
            echo 'Started the build'
        }

        stage('Build Image') {
            echo 'Build stage'
        }

        stage ('Push Image') {
            echo 'Push stage'
        }

        stage ('Update image tag in Helm') {
            echo 'Update image tag stage'
        }

        stage ('Deploy using Helm') {
            echo 'Deploy stage'
        }
    }

    post {
        always {
            echo 'Running tests'
        }

        failure {
            echo 'Pipeline run failed'
        }
    }
}