apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.service.port }}
  labels:
    {{- include ".deployment.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '200Mi'