name: K8s Exercise CI

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: true
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
            

            
